# For more information about the available options please visit: http://go/backstage (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: unity/rtl-creativecore-shaders
  name: rtl-creativecore-shaders
  description: "Support project for the Shader part of Creative Core"
  labels:
    costcenter: "3052"
  tags:
    - enterprise
  links:
    - url: https://unity.slack.com/messages/C070VN1A9/
      title: "#learn"
      icon: chat
spec:
  type: other
  lifecycle: pre-production
  owner: unity/real-time-learn-team
